config/routes.rb
Pinwheels::Application.routes.draw do
  resources :pinwheels

    root :to => 'application#index'

end

app/models/perk.rb
class Perk < ActiveRecord::Base
    belongs_to :pinwheel
end

app/models/pinwheel.rb
class Pinwheel < ActiveRecord::Base
    attr_accessible :name

    has_and_belongs_to_many :skills
end

app/models/skill.rb
class Skill < ActiveRecord::Base
    has_and_belongs_to_many :pinwheels
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery

    def index
        # Create pinwheels object
        $pinwheels = {}
        pinwheels = Pinwheel.joins{ skills }.includes{ skills }.order{ name }
        pinwheels.each do |pinwheel|
            $pinwheels[pinwheel.name.parameterize('_')] = {
                :unid => pinwheel.id,
                :name => pinwheel.name,
                :skills => pinwheel.skills.collect{ |s| s.name.parameterize('_') }
            }
        end
        
        # Create skills object
        $skills = {}
        skills = Skill.joins{ |s| s.pinwheels }.includes{ |s| s.pinwheels }.order{ name }
        skills.each do |skill|
            $skills[skill.name.parameterize('_')] = {
                :unid => skill.id,
                :name => skill.name,
                :pinwheels => skill.pinwheels.collect{ |p| p.name.parameterize('_') }
            }
        end

        render :template => 'index'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
!!!
%html
  %head
  %title Pinwheels
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

%body
  = yield

app/views/pinwheels/_form.html.haml
= form_for @pinwheel do |f|
  - if @pinwheel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pinwheel.errors.count, "error")} prohibited this pinwheel from being saved:"
      %ul
        - @pinwheel.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/pinwheels/edit.html.haml
%h1 Editing pinwheel

= render 'form'

= link_to 'Show', @pinwheel
\|
= link_to 'Back', pinwheels_path

app/views/pinwheels/index.html.haml
%h1 Listing pinwheels

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @pinwheels.each do |pinwheel|
    %tr
      %td= pinwheel.name
      %td= link_to 'Show', pinwheel
      %td= link_to 'Edit', edit_pinwheel_path(pinwheel)
      %td= link_to 'Destroy', pinwheel, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Pinwheel', new_pinwheel_path

app/views/pinwheels/new.html.haml
%h1 New pinwheel

= render 'form'

= link_to 'Back', pinwheels_path

app/views/pinwheels/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @pinwheel.name

= link_to 'Edit', edit_pinwheel_path(@pinwheel)
\|
= link_to 'Back', pinwheels_path